name: alkatrazpm
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependency_overrides:
  flushbar: "1.8.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^1.0.0
  carousel_slider: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  #http handler
  dio: ^3.0.9
  #local cache solution
  dio_http_cache: ^0.2.5
  # dependency injection
  get_it: ^4.0.1
  #user preferences
  shared_preferences: ^0.5.6+3

  json_annotation: ^3.0.0

  #sane snackbar
  flushbar: ^1.5.0

  toast: ^0.1.5

  crypto: ^2.1.3

  pointycastle: ^1.0.2

  enhanced_future_builder: ^1.0.2

  service_worker: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^3.2.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/poza1.jpg
    - assets/poza2.jpg
    - assets/poza3.jpg
    - assets/poza4.jpg
    - assets/poza5.jpg
    - assets/poza6.jpg
    - assets/poza7.jpg
    - assets/poza8.jpg
    - assets/poza9.jpg
    - assets/poza11.png
    - assets/poza12.png
    - assets/poza13.png
    - assets/poza14.png
    - assets/poza15.png
    - assets/confortable.png
    - assets/free.png
    - assets/open-door.png
    - assets/images/
    - assets/
  # To add assets to your application, add an assets section, like this:

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
